import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from ui_mywindow import Ui_MainWindow  # generated by pyuic5 from mywindow.ui


class MyApp(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # builds all widgets defined in Qt Designer

        # connect the button's "clicked" signal to our own function
        self.pushButton.clicked.connect(self.say_hello)

        self.click_count = 0

    def say_hello(self):
        self.click_count += 1
        self.label.setText(f"Button clicked {self.click_count} time(s)!")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MyApp()
    window.show()
    sys.exit(app.exec_())
