import sys
import os

import fastf1
import matplotlib
matplotlib.use("Qt5Agg")
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QMessageBox
from ui_mywindow import Ui_MainWindow  # generated by pyuic5 from mywindow.ui

CACHE_DIR = os.path.join(os.path.dirname(__file__), "f1_cache")
os.makedirs(CACHE_DIR, exist_ok=True)
fastf1.Cache.enable_cache(CACHE_DIR)


class MyApp(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  
        self.click_count = 0

    def setupUi(self, MainWindow):
        
        super().setupUi(MainWindow)  
        self.pushButton.clicked.connect(self.say_hello)

    def say_hello(self):
        self.click_count += 1
        self.label.setText(f"Button clicked {self.click_count} time(s)!")


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MyApp()
    window.show()
    sys.exit(app.exec_())
