# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yearLabel = QtWidgets.QLabel(self.centralwidget)
        self.yearLabel.setGeometry(QtCore.QRect(10, 10, 40, 25))
        self.yearLabel.setObjectName("yearLabel")
        self.yearSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.yearSpinBox.setGeometry(QtCore.QRect(55, 10, 70, 25))
        self.yearSpinBox.setMinimum(2018)
        self.yearSpinBox.setMaximum(2026)
        self.yearSpinBox.setProperty("value", 2024)
        self.yearSpinBox.setObjectName("yearSpinBox")
        self.gpLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.gpLineEdit.setGeometry(QtCore.QRect(135, 10, 160, 25))
        self.gpLineEdit.setObjectName("gpLineEdit")
        self.sessionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sessionComboBox.setGeometry(QtCore.QRect(305, 10, 70, 25))
        self.sessionComboBox.setObjectName("sessionComboBox")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.driverLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.driverLineEdit.setGeometry(QtCore.QRect(385, 10, 120, 25))
        self.driverLineEdit.setObjectName("driverLineEdit")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(515, 10, 140, 25))
        self.loadButton.setObjectName("loadButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(10, 45, 650, 20))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.canvasWidget = QtWidgets.QWidget(self.centralwidget)
        self.canvasWidget.setGeometry(QtCore.QRect(10, 75, 870, 500))
        self.canvasWidget.setObjectName("canvasWidget")
        self.reset_telemetria = QtWidgets.QPushButton(self.centralwidget)
        self.reset_telemetria.setGeometry(QtCore.QRect(850, 10, 41, 25))
        self.reset_telemetria.setObjectName("reset_telemetria")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "F1 Telemetry Dashboard"))
        self.yearLabel.setText(_translate("MainWindow", "Anno:"))
        self.gpLineEdit.setPlaceholderText(_translate("MainWindow", "Grand Prix (es. Monza)"))
        self.sessionComboBox.setItemText(0, _translate("MainWindow", "FP1"))
        self.sessionComboBox.setItemText(1, _translate("MainWindow", "FP2"))
        self.sessionComboBox.setItemText(2, _translate("MainWindow", "FP3"))
        self.sessionComboBox.setItemText(3, _translate("MainWindow", "Q"))
        self.sessionComboBox.setItemText(4, _translate("MainWindow", "R"))
        self.driverLineEdit.setPlaceholderText(_translate("MainWindow", "Codice pilota (es. VER)"))
        self.loadButton.setText(_translate("MainWindow", "Carica telemetria"))
        self.reset_telemetria.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
