# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.yearLabel = QtWidgets.QLabel(self.centralwidget)
        self.yearLabel.setObjectName("yearLabel")
        self.toolbarLayout.addWidget(self.yearLabel)
        self.yearSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.yearSpinBox.setMinimum(2018)
        self.yearSpinBox.setMaximum(2026)
        self.yearSpinBox.setProperty("value", 2024)
        self.yearSpinBox.setObjectName("yearSpinBox")
        self.toolbarLayout.addWidget(self.yearSpinBox)
        self.gpLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.gpLineEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.gpLineEdit.setObjectName("gpLineEdit")
        self.toolbarLayout.addWidget(self.gpLineEdit)
        self.sessionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sessionComboBox.setObjectName("sessionComboBox")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.sessionComboBox.addItem("")
        self.toolbarLayout.addWidget(self.sessionComboBox)
        self.driverLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.driverLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.driverLineEdit.setObjectName("driverLineEdit")
        self.toolbarLayout.addWidget(self.driverLineEdit)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.toolbarLayout.addWidget(self.loadButton)
        self.degradationButton = QtWidgets.QPushButton(self.centralwidget)
        self.degradationButton.setObjectName("degradationButton")
        self.toolbarLayout.addWidget(self.degradationButton)
        self.reset_telemetry = QtWidgets.QPushButton(self.centralwidget)
        self.reset_telemetry.setObjectName("reset_telemetry")
        self.toolbarLayout.addWidget(self.reset_telemetry)
        self.toolbarLayout.setStretch(2, 1)
        self.toolbarLayout.setStretch(4, 1)
        self.mainLayout.addLayout(self.toolbarLayout)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.mainLayout.addWidget(self.statusLabel)
        self.canvasWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasWidget.sizePolicy().hasHeightForWidth())
        self.canvasWidget.setSizePolicy(sizePolicy)
        self.canvasWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.canvasWidget.setObjectName("canvasWidget")
        self.mainLayout.addWidget(self.canvasWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "F1 Telemetry Dashboard"))
        self.yearLabel.setText(_translate("MainWindow", "Anno:"))
        self.gpLineEdit.setPlaceholderText(_translate("MainWindow", "Grand Prix (es. Monza)"))
        self.sessionComboBox.setItemText(0, _translate("MainWindow", "FP1"))
        self.sessionComboBox.setItemText(1, _translate("MainWindow", "FP2"))
        self.sessionComboBox.setItemText(2, _translate("MainWindow", "FP3"))
        self.sessionComboBox.setItemText(3, _translate("MainWindow", "Q"))
        self.sessionComboBox.setItemText(4, _translate("MainWindow", "R"))
        self.driverLineEdit.setPlaceholderText(_translate("MainWindow", "Codice pilota (es. VER)"))
        self.loadButton.setText(_translate("MainWindow", "Carica telemetria"))
        self.degradationButton.setText(_translate("MainWindow", "Degradazione gomme"))
        self.reset_telemetry.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
